"use client";

import { useState } from "react";
import { downloadResultCard } from "@/lib/result-sharing";

type ResultActionsProps = {
  title: string;
  shareUrl: string;
  summaryLines: string[];
  filename: string;
};

export default function ResultActions({
  title,
  shareUrl,
  summaryLines,
  filename,
}: ResultActionsProps) {
  const [feedback, setFeedback] = useState("");

  const note = (message: string) => {
    setFeedback(message);
    window.setTimeout(() => setFeedback(""), 2200);
  };

  const handleCopyLink = async () => {
    await navigator.clipboard.writeText(shareUrl);
    note("Link copied");
  };

  const handleShare = async () => {
    const text = summaryLines.join(" • ");

    if (navigator.share) {
      await navigator.share({
        title,
        text,
        url: shareUrl,
      });
      note("Shared");
      return;
    }

    await navigator.clipboard.writeText(`${title}\n${text}\n${shareUrl}`);
    note("Share text copied");
  };

  const handleDownload = () => {
    downloadResultCard({
      title,
      filename,
      summaryLines,
      footer: "Generated by Velmora",
    });
    note("Card downloaded");
  };

  return (
    <div className="rounded-2xl border border-white/70 bg-white/80 p-4 dark:border-white/10 dark:bg-slate-900/80">
      <div className="flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={handleCopyLink}
          className="rounded-xl bg-gradient-to-br from-cyan-400 via-violet-500 to-fuchsia-500 px-4 py-2.5 text-sm font-bold text-white shadow-[0_14px_28px_rgba(167,139,250,0.35)] transition hover:-translate-y-0.5 hover:shadow-[0_18px_36px_rgba(167,139,250,0.45)]"
        >
          Copy link
        </button>
        <button
          type="button"
          onClick={handleDownload}
          className="rounded-xl border border-white/70 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 transition hover:-translate-y-0.5 hover:text-slate-900 dark:border-white/10 dark:bg-slate-800 dark:text-slate-200 dark:hover:text-white"
        >
          Download card
        </button>
        <button
          type="button"
          onClick={handleShare}
          className="rounded-xl border border-white/70 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 transition hover:-translate-y-0.5 hover:text-slate-900 dark:border-white/10 dark:bg-slate-800 dark:text-slate-200 dark:hover:text-white"
        >
          Share result
        </button>
      </div>
      {feedback ? (
        <p className="mt-3 text-sm font-medium text-cyan-700 dark:text-cyan-300">{feedback}</p>
      ) : null}
    </div>
  );
}
